#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="1.1.8.1"
URL="http://sourceforge.net/projects/tomatocart/files/TomatoCart-v${VERSION}.zip"

dl $URL /usr/local/src

