#!/bin/sh -ex

DB_NAME=tomatocart
DB_USER=tomatocart
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/tomatocart
WORKDIR=/var/cache/tomatocart

# unpack and configure permissions
mkdir -p $WEBROOT
unzip $SRC/TomatoCart-*.zip -d $WEBROOT
rm $SRC/TomatoCart-*.zip
chown -R root:root $WEBROOT
chown www-data:www-data $WEBROOT/*.xml
chown www-data:www-data $WEBROOT/includes/configure.php
chown www-data:www-data $WEBROOT/includes/languages
chown www-data:www-data $WEBROOT/includes/work
chown www-data:www-data $WEBROOT/includes/logs
chown www-data:www-data $WEBROOT/ext/piwik/
chown www-data:www-data $WEBROOT/ext/piwik/config
chown www-data:www-data $WEBROOT/ext/piwik/config/config.ini.php
chown www-data:www-data $WEBROOT/admin/images
chown www-data:www-data $WEBROOT/admin/backups
chown www-data:www-data $WEBROOT/admin/includes/languages
chown www-data:www-data $WEBROOT/install/includes/languages
chown www-data:www-data $WEBROOT/install/templates/main_page/languages
chown www-data:www-data $WEBROOT/download
chown www-data:www-data $WEBROOT/templates
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/ext/piwik/tmp

# configure apache
a2dissite default
a2ensite tomatocart
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# setup work directory
mkdir -p $WORKDIR
chown -R www-data:www-data $WORKDIR

# curl based install
WEBROOT_ESC=$(echo $WEBROOT | sed "s/\//%2F/g")
WORKDIR_ESC=$(echo $WORKDIR | sed "s/\//%2F/g")
ADMIN_MAIL_ESC=$(echo $ADMIN_MAIL | sed "s/@/%40/")

URL="http://127.0.0.1/install"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL ${URL}/index.php
$CURL ${URL}/index.php?step=2
$CURL ${URL}/index.php?step=3

$CURL "${URL}/rpc.php?action=dbCheck&server=localhost&username=$DB_USER&password=$DB_PASS&name=$DB_NAME&class=mysql"

$CURL "${URL}/rpc.php?action=dbImport&server=localhost&username=$DB_USER&password=$DB_PASS&name=$DB_NAME&class=mysql&import=0&prefix="

$CURL ${URL}/index.php?step=4 --data "DB_SERVER=localhost&DB_SERVER_USERNAME=$DB_USER&DB_SERVER_PASSWORD=$DB_PASS&DB_DATABASE=$DB_NAME&DB_DATABASE_CLASS=mysql&DB_TABLE_PREFIX="

$CURL "${URL}/rpc.php?action=checkWorkDir&dir=$WORKDIR_ESC"

$CURL ${URL}/index.php?step=5 --data "HTTP_WWW_ADDRESS=http%3A%2F%2F127.0.0.1%2F&DIR_FS_DOCUMENT_ROOT=$WEBROOT_ESC&HTTP_WORK_DIRECTORY=$WORKDIR_SC&DB_SERVER=localhost&DB_SERVER_USERNAME=$DB_USER&DB_SERVER_PASSWORD=$DB_PASS&DB_DATABASE=$DB_NAME&DB_DATABASE_CLASS=mysql&DB_TABLE_PREFIX="

$CURL "${URL}/rpc.php?action=dbImportSample&server=localhost&username=$DB_USER&password=$DB_PASS&name=$DB_NAME&class=mysql&prefix="

$CURL ${URL}/index.php?step=6 --data "CFG_STORE_NAME=TurnKey+TomatoCart&CFG_STORE_OWNER_NAME=Store+Owner&CFG_STORE_OWNER_EMAIL_ADDRESS=$ADMIN_MAIL_ESC&CFG_ADMINISTRATOR_USERNAME=$ADMIN_NAME&CFG_ADMINISTRATOR_PASSWORD=$ADMIN_PASS&CFG_CONFIRM_PASSWORD=$ADMIN_PASS&DB_INSERT_SAMPLE_DATA=true&HTTP_WWW_ADDRESS=http%3A%2F%2F127.0.0.1%2F&DIR_FS_DOCUMENT_ROOT=$WEBROOT_ESC&HTTP_WORK_DIRECTORY=$WORKDIR_ESC&DB_SERVER=localhost&DB_SERVER_USERNAME=$DB_USER&DB_SERVER_PASSWORD=$DB_PASS&DB_DATABASE=$DB_NAME&DB_DATABASE_CLASS=mysql&DB_TABLE_PREFIX="

# tweak configuration
CONF=$WEBROOT/includes/configure.php
sed -i "s|HTTP_SERVER'.*|HTTP_SERVER', 'http://'.\$_SERVER['HTTP_HOST']);|" $CONF
sed -i "s|HTTPS_SERVER'.*|HTTPS_SERVER', 'https://'.\$_SERVER['HTTP_HOST']);|" $CONF
sed -i "s|HTTP_COOKIE.*|HTTP_COOKIE_DOMAIN', \$_SERVER['HTTP_HOST']);|" $CONF
sed -i "s|HTTPS_COOKIE.*|HTTPS_COOKIE_DOMAIN', \$_SERVER['HTTP_HOST']);|" $CONF
sed -i "s|ENABLE_SSL'.*|ENABLE_SSL', true);|" $CONF

# change default piwik admin username, and setup symlink for easy access
sed -i "s|login.*|login = \"$ADMIN_NAME\"|" $WEBROOT/ext/piwik/config/config.ini.php
ln -s $WEBROOT/ext/piwik $WEBROOT/piwik

# tweak services (disable gzip, enable seo friendly urls, enable piwik)
$MYSQL_BATCH --database=$DB_NAME --execute "DELETE FROM configuration WHERE configuration_key = 'SERVICE_OUTPUT_COMPRESSION_GZIP_LEVEL';"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO configuration VALUES ('', 'Create keyword-rich URLs', 'SERVICES_KEYWORD_RICH_URLS', 1, 'Create keyword-rich URLs for categories, products, articles and faqs.', 6, 7, NULL, '2012-05-23 10:42:56', 'osc_cfg_use_get_boolean_value', 'osc_cfg_set_boolean_value\(array\(1, -1\)\)');"

$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE configuration SET configuration_value = 'session;language;sefu;currencies;core;whos_online;simple_counter;category_path;recently_visited;breadcrumb;specials;reviews;piwik' WHERE configuration_key = 'MODULE_SERVICES_INSTALLED';"

# make sensitive non-world readable
chmod 640 $WEBROOT/ext/piwik/config/config.ini.php
chmod 640 $WEBROOT/includes/configure.php

# htaccess file not included in zip, wtf!?
mv $SRC/htaccess $WEBROOT/.htaccess

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

# cleanup
rm -f /tmp/cookie
rm -f $WORKDIR/*
rm -rf $WEBROOT/install

