#!/bin/bash -e
# regenerate tomatocart mysql password

. /etc/default/inithooks

CONF=/var/www/tomatocart/includes/configure.php
PASSWORD=$(mcookie)

sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$PASSWORD');|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=tomatocart --pass="$PASSWORD"

# clear working directory (ie. cache)
rm -f /var/cache/tomatocart/*

