#!/bin/bash -e
# regenerate tomatocart/piwik secrets and mysql password

. /etc/default/inithooks

WEBROOT=/var/www/tomatocart
T_CONF=$WEBROOT/includes/configure.php
P_CONF=$WEBROOT/ext/piwik/config/config.ini.php

DB_PASS=$(mcookie)
PIWIK_SALT=$(mcookie)
PIWIK_AUTH=$(mcookie)

sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$DB_PASS');|" $T_CONF
sed -i "0,/password/! {s/password.*/password = \"$DB_PASS\"/}" $P_CONF
sed -i "s|salt.*|salt = \"$PIWIK_SALT\"|" $P_CONF

PIWIK_QUERY="use tomatocart; UPDATE piwik_user SET token_auth=\"$PIWIK_AUTH\" WHERE login=\"piwik_view\";"

# update database
$INITHOOKS_PATH/bin/mysqlconf.py --user=tomatocart --pass="$DB_PASS" --query="$PIWIK_QUERY"

# clear working directory (ie. cache)
rm -f /var/cache/tomatocart/*

