#!/bin/bash -e
# set tomatocart/piwik admin password and email
# domain is set for piwik tracking, tomatocart is configured for all domains

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/tomatocart.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"

